site_name: spyreapi
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python: {}

watch:
  - src

markdown_extensions:
  - admonition
  - toc:
      permalink: true

nav:
  - Home: index.md
  - API Reference:
      - Client: api/client.md
      - Inventory: api/inventory.md
      - Spire: api/spire.md
      - Sales: api/sales.md
      - Communications: api/crm.md
      - Customers: api/customers.md
